ALTER TABLE users
ADD COLUMN phone VARCHAR(20) DEFAULT NULL,
ADD COLUMN address TEXT DEFAULT NULL,
ADD COLUMN city VARCHAR(100) DEFAULT NULL,
ADD COLUMN state VARCHAR(100) DEFAULT NULL,
ADD COLUMN pincode VARCHAR(20) DEFAULT NULL;